In [36]:
from konlpy.tag import Komoran
import numpy

komoran = Komoran()
text = "오늘은 구름이 많은 날씨네요"

nouns = komoran.nouns(text)
print(nouns)


# 각 명사에 dics key 부여 (0,1,2)
dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

['오늘', '구름', '날씨']
{'오늘': 0, '구름': 1, '날씨': 2}


In [39]:
# dics의 크기 = 벡터 차원의 크기
nb_classes = len(dics)

# value 값을 리스트 형태로 변환
targets = list(dics.values())

# 단위행렬 만들어주는 Eye 함수 사용
one_hot_targets = numpy.eye(nb_classes)[targets]
print(one_hot_targets)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
